version: '3'

services:
  db:
    image: postgres:15.2-alpine
    container_name: laundrex-db-local
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 100M
        reservations:
          cpus: '0.025'
          memory: 50M
  # api:
  #   container_name: laundrex-api-local
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #     target: development
  #   ports:
  #     - '8080:8080'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev
